/**
 * Regenerate src/lib/countries.ts — the static ISO 3166-1 alpha-2 → English
 * name map used by formatCountry().
 *
 * The map is static (not Intl.DisplayNames at runtime) so country labels are
 * byte-identical on server and client; Intl's CLDR data differs between Node's
 * ICU and the browser's, which caused React hydration mismatches.
 *
 * Names are sourced from this Node's ICU, then the few verbose CLDR forms are
 * shortened to the common names modern browsers render. Re-run after a Node/ICU
 * upgrade if you want refreshed names, and eyeball the diff.
 *
 * Run:
 *   pnpm exec tsx scripts/gen-countries.ts
 */
import fs from "node:fs";
import path from "node:path";

const dn = new Intl.DisplayNames(["en"], { type: "region" });
const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

const map: Record<string, string> = {};
for (const a of LETTERS) {
  for (const b of LETTERS) {
    const code = a + b;
    let name: string | undefined;
    try {
      name = dn.of(code);
    } catch {
      continue;
    }
    if (name && name !== code) map[code] = name;
  }
}

// Override verbose CLDR forms (Node renders these long; browsers render short).
Object.assign(map, { HK: "Hong Kong", MO: "Macao", PS: "Palestine" });

const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
const body = entries.map(([c, n]) => `  ${c}: ${JSON.stringify(n)},`).join("\n");
const file = `// Generated by scripts/gen-countries.ts — do not edit by hand.
// ISO 3166-1 alpha-2 → English country name. Static so country labels are
// identical on server and client: Intl.DisplayNames data differs between Node's
// ICU and the browser's, which caused SSR/client hydration mismatches (e.g.
// HK: "Hong Kong SAR China" vs "Hong Kong").
export const COUNTRY_NAMES: Record<string, string> = {
${body}
};
`;

const out = path.join(process.cwd(), "src/lib/countries.ts");
fs.writeFileSync(out, file);
console.log(`Wrote ${out} with ${entries.length} entries.`);
